### ISSUE TITLE
Unexpected behavior when link added to toggle field

### ISSUE THREAD

**Issue by neerro** [stefan-niedermann/nextcloud-deck#1013]
**Describe the bug and Steps to reproduce the behavior:**
You will find all steps and behavior on added [video link](https://youtu.be/UIAj5SquCm0)

**Expected behavior**
Toggle box should be work separate from main text field and needed possibility use link for open.

**Screenshots**
Video file on the link above

**Versions**
 - Nextcloud: latest
 - Nextcloud Deck: latest
 - Nextcloud Android: latest
 - Nextcloud Android Deck: latest

**Smartphone (please complete the following information):**
- Device: Honor 10 lite
- Android-Version: 10
- App-Store:
  - [x] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**

**Comment by stefan-niedermann** [comment]
While clicking in the empty space after the text is intented behavior (Tasks can be multiple lines long and are therefore treated as block elements rather than inline elements), i agree that clicking on the link should open that link.

Thank you very much for the videos, this will be very helpful for working out bugfixes.

**Comment by stefan-niedermann** [comment]
This issue has successfully been [fixed upstream](https://github.com/stefan-niedermann/nextcloud-notes/pull/1260).  
The fix will be published with **Deck Android `1.19.0`**.
