### ISSUE TITLE
"Add a new card" widget for home screen

### ISSUE THREAD

**Issue by molivier-fcms** [stefan-niedermann/nextcloud-deck#1035]
**Is your feature request related to a problem? Please describe.**
In quick menu (top screen menu) we can add the button "Add a new card". But we don't have the same widget for home screen so we could create a card with one press on the widget icon (as we have with Notes android).

**Describe the solution you'd like**
Having a widget for creating a new card from home screen.

**Extra question**:
When we add a new card from quick menu, we arrive in an intermediate panel for choosing which board and list where to create the note. Is it possible to also add the possibility to preset the target board and list so we arrive directly in the new note?

**Comment by stefan-niedermann** [comment]
Dear @molivier-fcms,
thank you for the feature request.

However, we have no plans to add a widget for this use case as it has several drawbacks (and we plan to remove it from the Notes app in a future release, too).
One of the drawbacks is inconsistent behavior (for example we needed to add the text ourself or have no text at all). We also can't detect which shape your icons on your launcher have per default, so it will always feel like a foreign item.

However, you can use either our Quick tile to quickly add new items:

![quick-settings-tile](https://user-images.githubusercontent.com/4741199/123636119-c58d7c80-d81c-11eb-81b5-5e70ef36cba3.gif)

The shortcut might not be directly visible in your quick settings, but usually you can edit them to raise its position (depending on manufacturer and ROM).

Alternatively use the native shortcuts (available since Android 7 i think) by long pressing on the launcher. Those items can be pinned to your homescreen imitating the desired widget behavior:

![shortcut](https://user-images.githubusercontent.com/4741199/123636205-ddfd9700-d81c-11eb-86af-d06a1b0d02c2.gif)

Regarding to your extra question:

Starting with version `1.19.0` the creation of a card and editing it, will be two separate steps. On one hand it will allow us to make the maintenance way easier and focusing on implementing new stuff, on the other hand it will allow to quickly add item without loosing the context due to switching the activity.
For this reason, [a title will be required *before* entering the edit mode](https://github.com/stefan-niedermann/nextcloud-deck/pull/1010), forcing the user to enter the title in an intermediate step. Now since we will have this intermediate step in any case, we will keep the option to switch target boards and lists. It currently will preselect the last visited board / list. Creating a customized launcher which preselects other boards and lists would require configuration screens, storing the properties and managing the creation and deletion of those dynamic shortcuts and is therefore currently not on our roadmap. This is a design decision which we might reevaluate in the future, also depending a bit on how often this feature will be requested.

**Comment by molivier-fcms** [comment]
Sure, thanks for these information. I did not pay attention about the native shortcut system. It fulfill my need. ;)
