### ISSUE TITLE
Not usable if internet connection is unstable

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [stefan-niedermann/nextcloud-deck#1061]
Desciption:
If the internet connection is disconecting from time to time (for example on the go) or you wanna use the app offile you will receive every few minutes a syncronisation error.
An offline mode would be nice, so that you can delete items from the list or add some and as soon as you again have network it does the sync. The sync as well as the trying to sync would be nice in the background without everytime needing to click on ignore. 
==> I know there is background sync, but when I add a new item or remove it, it with force tries to sync and fails and i need to always click on ignore error (see exception)

1.) Get unstable internet
2.) Remove items or add them to list
3.) Receive sync errors

**Expected behavior**
Offline Syncronisation: Kepps elemets in cache till the internet works again and then syncs/merges it in case others had made some changes before, without every few minutes receiving sync erros.

**Versions**
 - Nextcloud: latest
 - Nextcloud Deck: 1.4.3
 - Nextcloud Android: 3.16.1
 - Nextcloud Android Deck: 1.19.0

**Smartphone (please complete the following information):**
- Device: Samsung Z Fold 2
- Android-Version: 11
- App-Store:  Google Play Store

the error I will attache, next time it happens

**Comment by stefan-niedermann** [comment]
Hi @MrLoverLoverMMMM ,

thank you for picking up my offer to discuss this issue. At the Play Store developers are limited to 350 characters which makes a conversation ... well. ridiculous :wink: 

First of all, please define what `latest` is, as this varies depending on your environment (for example: the "latest" Deck Server app for Nextcloud 20 is 1.2.8, for Nextcloud 21 is 1.4.3 and Nextcloud 22 it will be 1.5).

Secondly: The app **does** support offline states (otherwise we would not have advertised it). We had an issue in a few versions of the Deck Android app though, which makes it the more important to be precise about the exactly used version. You can find it in the "About" section of the sidebar.

> a syncronisation error

Please, don't hide the error from us. We want to help and we need to know *which* error there was. I think there should be even a <kbd>Copy</kbd> button to make it easy to share the exact error message with us :slightly_smiling_face: I believe i saw something related to a LAN set up in your Play Store review before you quickly removed everything again :smile: Please share this again here as it is not the default setup which is used by the majority of the users. Maybe we missed something in this area.

> The sync as well as the trying to sync would be nice in the background without everytime

Check the settings of the app. There *is* a background sync available. Default is each `15 minutes` i guess, of course also each time when opening the app or performing an action. I recommend to disable the battery "optimizations" of Samsung for the Nextcloud and the Nextcloud Deck apps.

So, **TL;DR** just as at the Play Store: **We *want* to help you, but you will need to be a bit more verbose.** I hope you understand that "Get unstable internet connection" is not exactly an easy step to reproduce.

**Comment by stefan-niedermann** [comment]
@MrLoverLoverMMMM any news from you?

A few more hints about your setup would also be useful. I assume that your Nextcloud is only reachable in your private Wi-Fi, is this correct?

Keep in mind that "Offline capabilities" mean, that we can handle that your *device* is offline, not your server. So i am asking myself, why your server is not reachable the whole time?

Given you can only access your Nextcloud instance in your private Wi-Fi, you could simply enable "Sync only on Wi-Fi" in the Deck Android settings to match your setup.

**Comment by MrLoverLoverMMMM** [comment]
Hello ;)
Nope of course not, I have a whole datacenter and its of course from outside reachable as well!
My Server is reachable, but when my phone has instable connection at for example hotspots in shops, it fails from time to time to sync and annoyes with that.

**Comment by stefan-niedermann** [comment]
Thanks for the quick response 👋 🙂 

I am asking because this is a part of the message you posted in your Play Store review before deleting it

```
com.nextcloud.android.sso.exceptions.UnknownErrorException: failed to connect to /localip (port 8080) from /localip (port
```

and `/localip (port 8080)` sounds a bit cumbersome as a remote address.
Are you able to provide a test account? (if yes, please share the credentials with info@niedermann.it)

Unreliable network connectionsare always an issue. Of course we need to notify the user in case a synchronization was not successful (otherwise people would complain about failing sync without any further info). And given a sync is running while the network connection gets killed, for example when switching from wi-fi to mobile data, the sync will fail. So it's a bit of a dilemma here...

**Comment by stefan-niedermann** [comment]
Please see [this comment](https://github.com/stefan-niedermann/nextcloud-deck/issues/1063#issuecomment-888232487) in a similar issue. Starting with `1.19.1` we will handle this kind of infrastructure related errors silently and only display them if a user actively pulls down to refresh.
Thank you for the report :) You can delete the test account you created for me.

**Comment by stefan-niedermann** [comment]
(And with "infrastructure related" we explicitly mean also network related errors. As you are working on a datacenter, it is more likely that the connection aborts you noticed are related to the infrastructure *between* your device and the datacenter, for example cancelled calls when switching between wi-fi and mobile)

**Comment by MrLoverLoverMMMM** [comment]
Thx
-------- Ursprüngliche Nachricht --------Von: Niedermann IT-Dienstleistungen ***@***.***> Datum: 28.07.21  15:00  (GMT+01:00) An: stefan-niedermann/nextcloud-deck ***@***.***> Cc: MrLoverLoverMMMM ***@***.***>, Mention ***@***.***> Betreff: Re: [stefan-niedermann/nextcloud-deck] Not usable if internet
  connection is unstable (#1061) 
(And with "infrastructure related" we explicitly mean also network related errors. As you are working on a datacenter, it is more likely that the connection aborts you noticed are related to the infrastructure between your device and the datacenter, for example cancelled calls when switching between wi-fi and mobile)
