### ISSUE TITLE
Current Version of Android App does not qork in intranet or from outside

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [stefan-niedermann/nextcloud-deck#1090]
Error
Proxy at wlan used
Nextcloud 21.0.5
Deck App: 1.19.3
Deck on Server: 1.4.3
```
App Version: 1.19.3
App Version Code: 1019003
Server App Version: 1.4.3
App Flavor: play

Files App Version Code: 30170090

---

OS Version: 4.19.113-21591781(F916BXXU1DUF1)
OS API Level: 30
Device: f2q
Manufacturer: samsung
Model (and Product): SM-F916B (f2qxeea)

---

com.nextcloud.android.sso.exceptions.UnknownErrorException: failed to connect to localhost/127.0.0.1 (port 80) from /127.0.0.1 (port 56289) after 60000ms: isConnected failed: ECONNREFUSED (Connection refused)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by MrLoverLoverMMMM** [comment]
This issue occurs, when you switch between wifi and celular network and donot close the normal nextcloud app (not deck app).
if you close after switch the nextcloud app manually, then it will work

**Comment by desperateCoder** [comment]
@MrLoverLoverMMMM thanks for your report. Please fill out the issue template next time, it is there [for a reason](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#why-has-my-bug-report-been-closed).

When you switch your connectivity to cellular, does the **Files** app still work? By that I mean, can you still up- and download files without restarting it?

Spoiler: This most likely isn't a problem of the Deck app, but maybe caused by the Files app or the Single-Sign-On library we use to communicate with the files app. None the less we'll try to help to solve this issue.

**Comment by MrLoverLoverMMMM** [comment]
No also not
-------- Ursprüngliche Nachricht --------Von: Artur ***@***.***> Datum: 24.08.21  11:22  (GMT+01:00) An: stefan-niedermann/nextcloud-deck ***@***.***> Cc: MrLoverLoverMMMM ***@***.***>, Mention ***@***.***> Betreff: Re: [stefan-niedermann/nextcloud-deck] Current Version of Android App
  does not qork in intranet or from outside (#1090) 
@MrLoverLoverMMMM thanks for your report. Please fill out the issue template next time, it is there for a reason.
When you switch your connectivity to cellular, does the Files app still work? By that I mean, can you still up- and download files without restarting it?
Spoiler: This most likely isn't a problem of the Deck app, but maybe caused by the Files app or the Single-Sign-On library we use to communicate with the files app. None the less we'll try to help to solve this issue.

**Comment by desperateCoder** [comment]
Thanks for your quick response! The Problem isn't Deck or SSO then, but the [Files app](https://github.com/nextcloud/android). Please open an issue in the linked repository and describe the problem in the Files app. As soon as the problem is solved in the Files, Deck will automatically start to work again as well.

The cause why we can't do anything here, is that we as the Deck app don't make any server requests by ourself. We use a library called SSO to get the Files app do the requests, so you don't have to enter your credentials into our app and we don't need to mess with self signed certificates, security and stuff. The nextcloud Files app did already solve all of these issues and is trusted and secure. This way we can't make any mistakes risking your privacy and security.

**Comment by MrLoverLoverMMMM** [comment]
OkPerfekt
-------- Ursprüngliche Nachricht --------Von: Artur ***@***.***> Datum: 24.08.21  11:43  (GMT+01:00) An: stefan-niedermann/nextcloud-deck ***@***.***> Cc: MrLoverLoverMMMM ***@***.***>, Mention ***@***.***> Betreff: Re: [stefan-niedermann/nextcloud-deck] Current Version of Android App
  does not qork in intranet or from outside (#1090) 
Thanks for your quick response! The Problem isn't Deck or SSO then, but the Files app. Please open an issue in the linked repository and describe the problem in the Files app. As soon as the problem is solved in the Files, Deck will automatically start to work again as well.
The cause why we can't do anything here, is that we as the Deck app don't make any server requests by ourself. We use a library called SSO to get the Files app do the requests, so you don't have to enter your credentials into our app and we don't need to mess with self signed certificates, security and stuff. The nextcloud Files app did already solve all of these issues and is trusted and secure. This way we can't make any mistakes risking your privacy and security.
