### ISSUE TITLE
 Reorderable Tags

### ISSUE THREAD

**Issue by TomSaw** [stefan-niedermann/nextcloud-deck#1095]
Just a little drag&drop handle to the right of each Tag. Well known from other lists

This would be awesome 🤪

**Comment by stefan-niedermann** [comment]
Hey @TomSaw :wave: 

the tags currently do not have a order at all. This means, we can't reorder them because those changes won't be synchronized to the server and across devices.

I recommend you to request this feature in the [Deck server app](https://github.com/nextcloud/deck/issues/new?assignees=&labels=&template=Feature_request.md) - if they implement an order attribute for tags, the Android app can and will of course follow :)

**Comment by TomSaw** [comment]
Thanks Stefan for the quick response,

Will do so when I'm back home and reference this issue here afterwards.

**Comment by stefan-niedermann** [comment]
Perfect :slightly_smiling_face: I am watching the Deck server app repository too and will reopen this issue if the feature has been implemented in the Deck server app.
