### ISSUE TITLE
Possible Racecondition During Upload Of Multiple New Comments

### ISSUE THREAD

**Issue by jancwe** [stefan-niedermann/nextcloud-deck#1100]
**Describe the bug**
When sending multiple comments, while the connection is bad, the order gets messed up as soon as they get uploaded.

1. Turn off the internet connection
2. Write some comments
3. Turn on the connection
4. Order of comments changes during upload

**Expected behavior**
Order of added comments should stay the same.

**Possible solution**
 
A possible solution would be to use a work queue for uploading the comments in a fixed order.

The jetpack way would be to use the [WorkManager](https://developer.android.com/reference/androidx/work/WorkManager) I suppose.

**Comment by stefan-niedermann** [comment]
Sooo, we dug today into this shithole and *most* of the pitfalls are not our fault™. I think we have found a solution though which is satisfying.

**Problem No. 1:** The Nextcloud server does not allow clients to tell it the creation date. The server just assumes that the posted comment was created at the time the network request arrived. This means: You are offline on monday and post a comment. You go online on tuesday, after the sync the comment says it was created on tuesday. This is nothing we can fix unfortunately, you would need to add [create an issue in the server repository](https://github.com/nextcloud/server/issues/new?assignees=&labels=enhancement%2C+0.+Needs+triage&template=Feature_request.md) for that.

**Problem No. 2:** The Nextcloud server does store date information only based on seconds. So if you go back online on tuesday, the sync will post all comments which have been made while you have been offline on monday. Assuming you made 10 comments on one card in this time, they are all created at the same moment (form point of view of the Nextcloud server). The Android app might have mixed up the order, because we only relied on the creation date in the past. The Deck server app does by the way the same mistake (i'll open an issue there later).

**Our solution:** We aren't able to fix Problem No. 1 as it is not caused by the Deck Android app, but we can now guarantee that the order of the comments is correct in the Deck Android app after synchronizing again by not only sorting by creation date but also by the sequential of the comments as secondary parameter.

This improvement will land in `1.19.4` - happy to hear feedback :slightly_smiling_face: 

> The jetpack way would be to use the WorkManager I suppose.

Thanks for the suggestion, but i'm afraid it's not that easy - we have a quite complex synchronization mechanism as comments rely on cards which rely on stacks which rely on boards which rely on the account :wink:
