### ISSUE TITLE
card details => order tags by name

### ISSUE THREAD

**Issue by raphaotten** [stefan-niedermann/nextcloud-deck#1119]
When viewing the tags in a lot of places, they're ordered via name. So structuring them with numbers is possible for example.
When viewing them in the app "card detail" view, they're ordered in another manner. Is it possible to change it for consistency?

**Comment by stefan-niedermann** [comment]
I agree that the tags should be ordered alphabetically in the places below. The ordering of the proposals should stay as it is (It is currently ordered by occurrence count, so that the most often used tags will be at the top)

![grafik](https://user-images.githubusercontent.com/4741199/136771701-f9bfb36c-b5f0-4bee-b5da-c8a2fbb183f9.png)
![grafik](https://user-images.githubusercontent.com/4741199/136771708-f606d1b9-d84c-4c3b-b572-ef38320ef1e2.png)

@desperateCoder i guess you will want to do the ordering on the database level?

**Comment by desperateCoder** [comment]
@raphaotten Alright then. I just merged that, it will be shipped with the next version (1.19.5).

Thanks for your request!
