### ISSUE TITLE
Print markdown output as pdf to share content

### ISSUE THREAD

**Issue by nextexplorer** [stefan-niedermann/nextcloud-deck#1192]
**feature request**

Sometimes I really miss a functionality in the deck app to print the markdown output (with pictures) as a pdf. This would be very helpful to share the content with someone who does not use the nextcloud and would like to see an easy to read pdf.  
The option "Inhalt teilen" only extracts the markdown codes, which for example can't show the picture, which are only in the nextcloud.  

I would really appreciate a option to print a pdf in the app and also in the nextcloud-deck webserver ;)

**Comment by stefan-niedermann** [comment]
I see the use case to share information with people outside of your Nextcloud. However the solution approach is only fighting symptoms in my point of view.

The actual solution is to provide a public share via the Nextcloud Deck server app ([see also](https://github.com/nextcloud/deck/issues/14)). Introducing a PDF export will lead to
- "I want configuration options for the PDF output!"
- "I want to export in other formats!"
- and last not least: An exported PDF is only a snapshot - it will cause confusion since the actual content will evolve and change, new comments will be made etc.. The exported file is only a snapshot and can not be up to date.

I therefore suggest to upvote the corresponding issues in the Deck server app repository - Thanks for the request, but sorry: We have currently no plans to implement such a feature in the Deck Android app.
