### ISSUE TITLE
Enhanced support for Projects

### ISSUE THREAD

**Issue by crispyduck00** [stefan-niedermann/nextcloud-deck#1289]
Hi, I know it is on the readmap but would like to ask if we can expect more project features, hopefully also adding a card to a project in near future?

Br
cripyduck

**Comment by desperateCoder** [comment]
Hi @crispyduck00 , thanks for your request!

To be honest, we didn't really work with projects, so this would need some more research. The API documentation doesn't contain a block regarding projects either ( see https://deck.readthedocs.io/en/latest/API/#cards)

That's not a showstopper, we still can sniff what the WebApps does, just want to say it might take some time. 

But as you are here: what features / actions would you like to have, and what order of implementation would you wish / suggest?

To be honest, we have a quite nasty other bug with higher priority for now, but this issue here could be a candidate for a slightly bigger leap, so I'm looking forward to your feedback.

**Comment by crispyduck00** [comment]
Hi @desperateCoder , thanks for the fast answer.

What I would really need is a way to link cards to contacts. The idea behind projects is the possibillity to link thinks also frim different apps together.
Anyway contacts is not supporting it now, bit I use some "dummy" project per contact to  link cards and also files to it.
So it would be nice to be able to link cards to at least existing projects directly in the app.

Some other things I am actually missing is "deleting attachments" and what would be really nice is a board overview view. I know a smartphone screen is small, but some kind of view like it is available in the 5/7day few in every calendar app.
The nice/good thing about kanban is to see everything on one board. 

Best regards,
cd

**Comment by aljawaid** [comment]
> and what would be really nice is a board overview view. I know a smartphone screen is small, but some kind of view like it is available in the 5/7day few in every calendar app. The nice/good thing about kanban is to see everything on one board.
- _if that could rotate to landscape too then we could see more_

**Comment by stefan-niedermann** [comment]
[Projects](https://github.com/nextcloud/server/issues/28320) has been deprecated started with Nextcloud 25 Hub 3 - We will continue with the replacement "Related Resources" in #1368
