### ISSUE TITLE
Feature Request: Clone Cards

### ISSUE THREAD

**Issue by aljawaid** [stefan-niedermann/nextcloud-deck#1297]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**
1. Cards can be moved but not cloned currently.

**Describe the solution you'd like**
1. Allow cards be cloned, just like the app allows boards to be cloned

**Describe alternatives you've considered**
Revert to Deck on Web

**Additional context**
> Beware though, that this will probably not allow cloning attachments or comments just like the clone feature when cloning a board together with its cards.
- _At least with a warning notice, we could clone the basic card and description etc. Something is better than nothing._
[Some General Feedback on Deck for Android #1290](https://github.com/stefan-niedermann/nextcloud-deck/issues/1290#)

**Comment by aquananu** [comment]
I have a little variation to this request

We should be able to create clone of card just as a link to the original card, this will help the user to create a board with cards they are associated or assigned, rather than following up on different boards and getting notification for all cards from all boards this is like having favorites in cards

Secondly, option not to turn off sync a particular board on mobile.

I m requesting this to reduce the data that needs to be synced on mobile app so user will be able to monitor cards which he has on his personal.
