### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by R4U5CH1337** [stefan-niedermann/nextcloud-deck#13]
Hi
I was wondering how to install the code or zip to my Fairphone 2 LOS 15.1 (or how to install it generally on Android) - do you have any advice for me? I'm new with this topic.

Thanks a lot and thanks for the great work so far.

**Comment by desperateCoder** [comment]
Hi,

Currently this app is in alpha stadium, doesn't do much at all. 

If you still want to install it, you would need an Android Studio running on your computer (IDE for Android), check out the code and build it manually. 

Right now, there isn't a prebuilt APK, since it would change quite often and take time we subsequently can't put in development.

**Comment by R4U5CH1337** [comment]
Hi.
I see. So I'll follow you and check your progress here. Think this app will be really handy one day.

Vielen lieben Dank für die schnelle Antwort!

**Comment by desperateCoder** [comment]
Yes, I think that's the way to go. As soon as we have a quite reliable viewer-functionality, we will release a build, then start adding more features.

Gerne, Danke für dein Interesse!
