### ISSUE TITLE
Be able to select if calendar should start on Sunday or Monday

### ISSUE THREAD

**Issue by johanbook** [stefan-niedermann/nextcloud-deck#1322]
When picking due dates for a card the calendar starts the week on Sunday for me. I would be great if it was possible to have an option in the settings that weeks start on Monday which is common in e.g. Europe.

I greatly appreciate the app otherwise!

**Comment by stefan-niedermann** [comment]
Thanks! This is a setting that should not be done in any app but depend on the location you set globally on your smartphone:

As you see, we respect the your locale and the week starts with sunday in case you for example chose `United States` rather than `Germany`:

| DE | US |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/4741199/199756601-381afb19-5766-44e2-978d-5e370262b8a9.png) | ![image](https://user-images.githubusercontent.com/4741199/199756500-a048127b-580f-4e6f-9321-02c426edf7a1.png) |

Be aware that you can also set your language to english while the location is germany.
The global Android settings look usually something like this, depending on your your manufacturer and Android version:

![image](https://user-images.githubusercontent.com/4741199/199756361-59472db9-873c-422c-a1e1-6635ace26ba8.png)
