### ISSUE TITLE
When a stack is renamed from the web interface, its name does not change in the Android application, despite a refresh

### ISSUE THREAD

**Issue by Jerome-Herbinet** [stefan-niedermann/nextcloud-deck#1332]
**Describe the bug**

When a stack is renamed from the web interface, its name does not change in the Android application, despite a refresh or even after having flushed application cache.

1. Go to the web interface and rename a stack
2. Refresh the app (swipe down)
3. Notice tha the name of the stack doesn't change

**Expected behavior**
The name should change after a refresh or after killing and retarting the app

**Versions**
 - Nextcloud: 24.0.4
 - Nextcloud Deck: 1.7.1
 - Nextcloud Android: 12
 - Nextcloud Android Deck: 1.20.2

**Smartphone (please complete the following information):**
- Device: Xiaomi 11T
- Android-Version:  12
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [X] F-Droid
  - [ ] Huawei AppGallery

I can provide logs if necessary.

**Comment by desperateCoder** [comment]
Hi @Jerome-Herbinet, thanks for your Report!

This is unfortunately a known issue we can't fix, since it is the server not updating the ETags properly, see: https://github.com/nextcloud/deck/issues/2866

As soon as the server app is fixed, the problem will vanish on our side.

As a quick fix you can disable etags in your Android-Deck-App settings.

As I see you contribute to Nextcloud, you can also consider fixing the issue by providing a pull request at the server repo (see linked issue above) 😉

**Comment by Jerome-Herbinet** [comment]
Thank you @desperateCoder ; I may suggest one thing : What do you think about adding a "Known issues" section in /blob/master/README.md which would explain the problem and the Etags tip ? I can do it.

**Comment by stefan-niedermann** [comment]
I guess a hint in the [`FAQ.md`](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md) would make sense, yeah... Will add a section, thanks for the idea 🙂

**Comment by Jerome-Herbinet** [comment]
Great ! ... and I recommend you to add a link to the FAQ in the README.md :-)
