### ISSUE TITLE
Request: APK Releases on Github

### ISSUE THREAD

**Issue by S7venLights** [stefan-niedermann/nextcloud-deck#1352]
Simply so we can update with Obtanium or Octodroid.

**Comment by stefan-niedermann** [comment]
Why don't you use the F-Droid builds?

**Comment by S7venLights** [comment]
I like getting fast updates from Github and I like that Github apps have their own signing keys, which avoids the single fail point of fdroid builds.
See https://github.com/ImranR98/Obtainium
For a better description.

**Comment by stefan-niedermann** [comment]
Sorry, but we do currently not have any plans to release production builds directly here at GitHub, especially because of a missing upgrade mechanism which might cause outdated (maybe in terms of security critically) apps for users who install apk files from this source without a proper store like F-Droid, Play Store or others.

> which avoids the single fail point of fdroid builds.

This is false, given GitHub is a monolithic proprietary cloud service - a breach would affect all released apks here because the signing keys would havw to be trasmitted to and stores at GitHub in plain unencrypted text, so the issue you are concerning is not avoided here.

**Comment by S7venLights** [comment]
Okay, thanks for the info 🙏
