### ISSUE TITLE
Use credentials from Nextcloud Files, Talk, Notes or News app

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/nextcloud-deck#14]
Since this is another of the cool suite of Nextcloud Android apps, it would be great if it would take the credentials automatically too. :) Maybe that’s already planned?

cc @David-Development @AndyScherziner @tobiasKaminsky

**Comment by juliushaertl** [comment]
Yes, this is already implemented. The app will use the files apps new single sign on. :wink:

**Comment by jancborchardt** [comment]
Wow, in pre-alpha and already great! :tada: :)

**Comment by tobiasKaminsky** [comment]
@jancborchardt just for clarification, the current SSO only works with Files, so it cannot take credentials from Talk, News, … as stated in title.
It also not planned to have any apps serving as "master" for SSO, only Files as a central app should do this.

**Comment by stefan-niedermann** [comment]
Right, we will try to have this as only authentication method with an information pop up in case a user has *only* deck installed and *not* the files app. User will get notified that the files apo is a required dependency and a redirect to the Play Store will be implemented.

We will see if we get much feedbackt of users who do not want to install the files app, but i dou t anyone will install only the deck app and not the files app.

**Comment by varac** [comment]
> We will see if we get much feedbackt of users who do not want to install the files app, but i dou t anyone will install only the deck app and not the files app

Hej, user here without the files app :) For me installing the file apps *only* to authenticate deck is too much of a burden because it will grant access of my smartphone to all my files stored in nextcloud, which I don't want to because of security concerns (I use the desktop files app but don't want my smartphone access the files).
So a different authentication method would be much appreciated.

**Comment by stefan-niedermann** [comment]
That's a pitty, but i'm afraid that this will not happen.

> only to authenticate deck

The way better UX is only a very small part of the advantages of this mechanism (and probably the only directly visible parts for users).

Other advantages are
- 🔒 Security benefits: The Deck app does no longer store a password itself. 
- 🔌 Reliability: All network activities are based on the official files app. This ensures the same support for self signed certificates, 2 factor authentication and many other edge cases
- 🚀 More time to implement and maintain the actual features

>  it will grant access of my smartphone to all my files stored in nextcloud

This means that you either don't trust the Nextcloud app or you don't trust the security concept of Android. Every app is completely separated and can only access files if the user has granted access.

Not trusting Android is absolutely valid (i don't neither :wink: ), but you should probably have a look into completely open source custom ROMs without any Play Services (like i do :wink: ) and only install Apps which you can trust, e. g. from F-Droid. Everything else is fixing symptoms instead of really fighting the true issues.
