### ISSUE TITLE
Internal file attachments generate bad links on app

### ISSUE THREAD

**Issue by jsox79** [stefan-niedermann/nextcloud-deck#1495]
Does not display the correct link for the file.  Generates a weird link with f/random number
Ex
Site.com/f/345
Which obviously doesn't exist.
Big problem, gonna need a refund if this can't even link to files.

**Comment by stefan-niedermann** [comment]
Yeah, I usually would ask you to fill out the issue template instead of ignoring or deleting it. I also usually would like to ask you for clear steps to reproduce and a well explanation, so I can answer your support request and help you in my freetime.

Then I read

> gonna need a refund if this can't even link to files.

Please just send me your Play Store Order ID or your GMail Account via mail (info@niedermann.it). I will refund your money.

I am tired of people trying to hold developers on ransom with shitty ratings and refunds.

**Comment by jsox79** [comment]
ok, i see where you are coming from, sorry to come of dickish.  i just expected the same functionality from the web in the mobile app.  can you please help?
the problem i think now looking at it from the mobile app side, is that the functionality to add an attachment to a card from nextcloud rather than uploading it doesnt exist.  which is probably why when it goes to read the attachment of cards already made that it doesn't know where the link goes to.  thanks
