### ISSUE TITLE
Notifications for due decks

### ISSUE THREAD

**Issue by tomtom** [stefan-niedermann/nextcloud-deck#1526]
**Is your feature request related to a problem? Please describe.**
The app relies on the Nextcloud app for handling notifications/alarms of due cards. Unfortunately, the Nextcloud app is broken (in this respect) and, depending on the setup, does not handle notifications.

**Describe the solution you'd like**
It would be really great if the Deck app would handle alarms/notifications on its own on the phone/tablet. The Deck app should not rely on the user's nextcloud server or the Nextcloud app for this.

**Additional context**
I use the current version of the app from the Google app store.

**Comment by stefan-niedermann** [comment]
Dear @tomtom 

thank you for your suggestion.

> The app relies on the Nextcloud app for handling notifications/alarms of due cards. 

This is correct and [described in our FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#how-to-receive-notifications-when-a-due-date-is-reached).

> Unfortunately, the Nextcloud app is broken (in this respect)

Upstream issues are no excuse for permanent workarounds in downstream projects. If there's an Android bug, you wouldn't expect each app to handle the issue, would you? Solving the issue at the proper place will also make other users benefit form the solution and prevent multiple implementations in low-on-resources projects (like this one :wink:)

> depending on the setup, does not handle notifications

By "setup" you probably mean missing Google Play Services? I agree that this is a bad limitation (given I don't have installed Play Services myself). However the solution can only be to fix this in the Nextcloud Android app for example by [a polling fallback (#7046)](https://github.com/nextcloud/android/issues/7046) or [implementing Unified Push (#8684)](https://github.com/nextcloud/android/issues/8684).

We currently do not have any plans to duplicate and maintain the notification logic of the Deck server app, the Nextcloud Android app, merging possible offline notifications (due date) from the Deck Android app and online notifications (assignments, updates) from the Deck server app to the Nextcloud Android app including conflict resolution (which is not even possible because we can't know whether the Nextcloud Android app does or does not show Deck notifications).

Refs: https://github.com/stefan-niedermann/nextcloud-deck/issues/208#issuecomment-609008692
