### ISSUE TITLE
Purchased app, but will not connect

### ISSUE THREAD

**Issue by wildernessfamily** [stefan-niedermann/nextcloud-deck#1575]
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Deck Android app, neither the [Deck server app](https://github.com/nextcloud/deck/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

I purchased NextCloud Deck app on the Google Play Store. I have NextCloud App on my iPad as well. The iPad app, I have no issues with. It's perfectly. After the installation of Android NextCloud Deck, it asks me to choose an account. My account show in the "Choose an account" list. It's the only account. I choose it. Click okay. It asks me, "Allow NextCloud Deck to access your NextCloud account myemai@domain.tld?. Which I choose `allow`. It then says importing boards for a second or two. Then it states:
"Oh no - What now. We could not determine the version of the server side Deck app. Please make sure it is installed and enabled. The account of your Nextcloud app might no longer be authorized. Yeta yeta... I clear the cache. I also tried clearing all storage. I uninstalled, and reinstalled the app. I logged out and logged back in. I had NextCloud Deck on my old Android phone, and it worked with no problem. I had installed it on my old phone with F-Droid.  I got a new phone, a Google Pixel 6a. I wanted to support the project as I use Deck a lot. I choose to purchase it on the Play store instead of using F-Droid. I did uninstall the app and tried the F-Droid app, but same problem. I'm not sure what else I can do.

### Expected behavior

Should connect and load my boards.

### Deck Android version

1.22.1

### Deck server version

1.11.3

### Nextcloud Android version

3.27.0

### Nextcloud version

27.1.3 NextCloud AIO

### Device

Google Pixel 6a

### Android Version

14

### App Store

- [X] Google Play Store
- [ ] Google Play Store (Beta channel)
- [X] F-Droid
- [ ] Huawei App Gallery

**Comment by desperateCoder** [comment]
Hi @wildernessfamily, thanks for reaching out to us!

That's a quite weird one, so I'd have some questions here:

- Does the Nextcloud files app work properly? (you see your data, you can upload stuff)
- do you still have any other device still working with your account?
- does the Deck web-app work when you login via browser?
- are there any changes on the server side since it last worked? 

My first guess would be some routing issues regarding the URL of the REST API we're interacting with. In case you have some reverse-proxy action going on there, we might not be aware of this. But first off: Answering the questions above will trim the problem down.

Sorry for the inconveniences, we'll do our best to get the bird flying again!

P.S.: I'm out for today, we have 00:45 AM here, I need to go to work tomorrow (just german things I guess? :man_shrugging: ), but still looking forward to your answers! I'll then answer tomorrow, pinkie promise! :wink:

**Comment by wildernessfamily** [comment]
I actually got it to work. This time, I went into the NextCloud app, cleared the cache/storage. Then uninstalled the NextCloud app. Reinstalled the NextCloud app. Generated a new security token for the NextCloud app. NextCloud app up and working again. Then went into the NextCloud Deck app and went through the process. This time it worked :)
Thanks for the quick response, and thanks for an awesome app.
