### ISSUE TITLE
Leap year issue

### ISSUE THREAD

**Issue by ossie** [stefan-niedermann/nextcloud-deck#1593]
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Deck Android app, neither the [Deck server app](https://github.com/nextcloud/deck/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

1. Open any card
2. Open the due date
3. Try to set the date to February 29th 2024

There is no such date in the calendar and all following days are shifted weekday wise. 

### Expected behavior

I should be able to select this date, as it is valid. It is actually today. 

### Deck Android version

1.23.4

### Deck server version

1.9.7

### Nextcloud Android version

3.28.0

### Nextcloud version

---

### Device

Fairphone 4

### Android Version

13

### App Store

- [ ] Google Play Store
- [ ] Google Play Store (Beta channel)
- [X] F-Droid
- [ ] Huawei App Gallery

**Comment by stefan-niedermann** [comment]
Hi @ossie

due to [insufficient theming capabilities](https://github.com/material-components/material-components-android/issues/2586) we decided to use `com.wdullaer:materialdatetimepicker` in favor of the default picker. I [reported your issue upstream](https://github.com/wdullaer/MaterialDateTimePicker/issues/756) to fix it for all users.

However, there is not much we can do on our side, so closing this in favor of the upstream issue.

Thank you for the report!
