### ISSUE TITLE
Add notifications/alarm for cards with a due date

### ISSUE THREAD

**Issue by nr458h** [stefan-niedermann/nextcloud-deck#160]
It would be great to get notifications about cards wich have a due date for today/ or the upcoming day.
In this way I wouldn't need to go through all cards to see, which of them have a due date.

**Comment by stefan-niedermann** [comment]
Sounds like a good feature. We will definitely consider it after completing the main features :)

But i have concerns, that it might not be reliable because of the battery optimizations of current ROMs.

**Comment by jakobroehrl** [comment]
I think we should give an battery optimization Info on the 1st start
It could be handy to give the user a hint.
Tutanota has the possibility to deactive the battery optimization with one click on the 1st start.

**Comment by stefan-niedermann** [comment]
We are currently relying on `WorkManager` which is battery optimized and the recommended way for recurring tasks. It has a minimum execution distance of 15 minutes. This should be enough for checking duedates and displaying notifications.

I don't see a reason to disable the android battery optimization here, but thank you for the hint.

**Comment by roboticsalign** [comment]
It would be great to get notified before/at the due date. An integration to the calendar would be sufficient for me, so the calendar app could handle the reminder: https://github.com/nextcloud/deck/issues/15  

Do you see further benefits of a seperated notification from the deck app?

**Comment by stefan-niedermann** [comment]
Well, only drawback is that we would assume that the user has calendar sync configured.

Of course i like the idea because it would keep the implementation and maintenance efforts small, but maybe we need to provide it as fallback though. (there are always people complaining that they don't want to have two separate apps for one purpose).

I'll try on my personal phone how it feels with reminders by calendar...

**Comment by EnRic0111** [comment]
Hey, thanks for the Deck Tool with Nextcloud. I'll just test to use nextcloud and its Apps for my Company, especially Deck. Its simple and works well. I just brought your mobile Android App Deck and checked if i get notifications from the notes i set. In here i saw you already working on it, great. If it's possible, you could implement the feature. Please let us know the progress in here. Many thanks in advance 👍

Anyway,  good job, the app works stable and fast, sync also.

**Comment by stefan-niedermann** [comment]
Actually this is already working in the meantime:

Since we have implemented Push Notifications a few releases ago, you will get notified in the app when a card reaches its due date.
No need for external solutions with calendar and stuff - the Deck server app sends a notification and the Android App handles it.

Indeed this is way better since any local solution within the App because the server app can send the Push Notification on various ways (like in the Browser and via E-Mail).

**Comment by stefan-niedermann** [comment]
PS.: There is a known issue with Push Notifications in the current release - but it is already fixed and will be shipped in `1.10.0`.
