### ISSUE TITLE
card's description of shared boards invisible with read only permission

### ISSUE THREAD

**Issue by Ornanovitch** [stefan-niedermann/nextcloud-deck#1635]
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Deck Android app, neither the [Deck server app](https://github.com/nextcloud/deck/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

1. As user A, create a board `plop` and share it with user B, with read-only permission
2. As user B, sync your boards with the android app, then select the board `plop` and open a card

Description is invisible (attachments, comments and activity are visible) - the bug is reproducible for all concerned users

| mobile | desktop |
|--------|--------|
| ![mobile](https://github.com/stefan-niedermann/nextcloud-deck/assets/34077099/2ccb8af1-71c3-4931-b68a-6647b16e9789) | ![desktop](https://github.com/stefan-niedermann/nextcloud-deck/assets/34077099/7133d941-6537-42ff-a347-5e39c6cf591b) | 

### Expected behavior

Description is visible (as in the web browser app)

### Deck Android version

1.24.1

### Deck server version

1.13.0

### Nextcloud Android version

3.29.0

### Nextcloud version

29.0.1

### Device

Galaxy A5 2017 (reproduced on multiple devices)

### Android Version

11

### App Store

- [ ] Google Play Store
- [ ] Google Play Store (Beta channel)
- [X] F-Droid
- [ ] Huawei App Gallery

**Comment by Ornanovitch** [comment]
I see no error in the app logs. The issue seems similar to this old one : https://github.com/stefan-niedermann/nextcloud-deck/issues/1401

**Comment by stefan-niedermann** [comment]
While I haven't been able to reproduce this very issue, I noticed some other issues that are related to the description field and the read only permission. I'll dig into this further within the bext few days. Thank you for your report!

**Comment by Ornanovitch** [comment]
Hey Stefan, any news on your side? Is there anything we can do to help you to progress on this?

**Comment by stefan-niedermann** [comment]
Not yet, I am currently a bit busy, but I didn't forget you. A Pull Request would of course be welcome, the root cause is probably in this method: https://github.com/stefan-niedermann/nextcloud-deck/blob/master/app/src/main/java/it/niedermann/nextcloud/deck/ui/card/details/CardDetailsFragment.java#L151

**Comment by stefan-niedermann** [comment]
Huh. Actually there might only one line missing in the `else` block:

```java
registerEditorListener(binding.descriptionViewer);
```

**Comment by Ornanovitch** [comment]
Thanks, no problem of course!

Ok! I'll reed this piece of code and try to see if I feel comfortable with opening a PR (I never tried to play with the dev of a mobile app..!), if you can't find time soon :)

Best!

**Comment by desperateCoder** [comment]
Hey, I don't really have the time to set up a proper test environment, but I had enough time to add the line.

Here's a DEV build of the app with the above change: [APK ԅ(≖‿≖ԅ)](https://github.com/stefan-niedermann/nextcloud-deck/actions/runs/9484236891/artifacts/1594115511)

You can install the APK right beside your version from F-Droid, you'll end up with an additional deck app with the label "DEV" on the icon. Just connect it to your account, let it sync and then please check if the issue is resolved for you.

Looking forward to your feedback! :blush:

**Comment by Ornanovitch** [comment]
Hi, thanks for those first attempts!

I tried both of your builds, the one from the Stefan's PR and the one from your branch desperateCoder, and sadly both of these apparently do not solve the issue. Worse, the title disappeared too :sweat_smile:  But maybe it's a clue?

![signal-2024-06-12-181805](https://github.com/stefan-niedermann/nextcloud-deck/assets/34077099/ada15189-9636-4179-af4d-49bcdd46c138)

_Note that we don't use the tags, neither the assign, nor the due date, so I don't know for those elements_
