### ISSUE TITLE
NullPointer Excecption when creating a new label

### ISSUE THREAD

**Issue by machinaeXlasse** [stefan-niedermann/nextcloud-deck#167]
**The bug**

I get this Error on every app startup:
``` Java
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Long it.niedermann.nextcloud.deck.model.Card.getLocalId()' on a null object reference
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardDataProvider.goDeeperForUpSync(CardDataProvider.java:171)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.StackDataProvider.goDeeperForUpSync(StackDataProvider.java:115)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.BoardDataProvider.goDeeperForUpSync(BoardDataProvider.java:112)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:93)
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager$1.lambda$onResponse$0(SyncManager.java:88)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$1$sy1r3klzPK3UdZB5T0drzwhw2Oc.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:764)
```

Unfortunately I can not really tell what I did right before.

I removed several boards from both my accounts using the webapp.
Also I was Synchronizing the second account shortly before the error.

I got a glimpse that all cards for the account that is opened on startup are updated correctly but for the other (I once managed quickly enogh to switch accounts) boards I deleted were still there.

Reinstalling the App (then reconnecting the accounts) brought everything back to normal. I couldn't reproduce the error yet but I'll try.

**To Reproduce**

Probably deleting Boards, than connecting acconts or the other way around.

**Smartphone:**
 - Device: Xperia XZ1 Compact
 - Android-Version: 9

Thanks for the software! I recognize you are making big leaps from verision to version. Love it.

**Comment by desperateCoder** [comment]
Hi @machinaeXlasse, really glad to hear you like our work!

Thanks for your report! I actually have same issue, for @stefan-niedermann it seems to work. Now I know it isn't my data constellation, so I can hunt this bug. 

Unfortunately it is in my code and not in Stefan's 😝 , so I'll have a look at it ASAP.

**Comment by desperateCoder** [comment]
@machinaeXlasse can you tell me the version of the android deck app you are using? I looked it up, the line mentioned in the stacktrace is empty in the current master branch, I'd like to have a look at the version installed on your device, but @stefan-niedermann is releasing every 2 seconds :stuck_out_tongue: , so i have a hard time diving into it without knowing your exact version.
You can look it up at the menu "About".

**Comment by desperateCoder** [comment]
ok, i dug into this, seems like a not properly synchronized Label is causing the sync to die... any chance, you had created a label while testing?

**Comment by machinaeXlasse** [comment]
I actually did create a label. It had worked, but only showed up after I left the card edit mode. Because it didn't come up right away I created the same label twice.

My version is 0.0.8 from F-Droid

**Comment by machinaeXlasse** [comment]
Just reproduced the error like this:
Created a label in card edit mode (add new)
Created the same label (add new)
Removed one of the two labels

**Comment by desperateCoder** [comment]
Ok, just as i thought.  The extra step, creating a second identical label isn't even breaking it. the label itself is. 
So, what happens is:
* You create a label and the sync triggered.
* First of all the board including the labels is synced
* Since the createLabel call is executed asynchronous, the sync doesn't wait for the response
* Then stacks and cards are synced, but they didn't change, matter of milliseconds
* Here is, where the problem begins: the card didn't change, but it has a label assigned
* I try to assign the Label, but the create is still running async...
* To assign it, i have to provide the Label-ID to the server, which doesn't exist yet
* Restarting the app won't help, since we trigger the same procedure at startup 
* -> Persistent death and damnation for our beloved app.

This is gonna be a tough one, the sync is very complex, since we try to provide full offline capabilities.

Please be patient with this one, if i fix this the quick way, you end up with a crappy app and i end up with guys like you hating my app :smile:

**Comment by machinaeXlasse** [comment]
Take your time! Still looking forward :-D
I'm happy I can already use it in many ways.

**Comment by stefan-niedermann** [comment]
Sorry, my bad!!

**Comment by desperateCoder** [comment]
Unfortunately blocked by https://github.com/stefan-niedermann/nextcloud-deck/issues/200

**Comment by desperateCoder** [comment]
My bad, #200 is a false positive. This one is going to be fixed next.

**Comment by desperateCoder** [comment]
Well... that's weird. The problem seems to be solved by an other change or something, it doesn't happen anymore...

@stefan-niedermann Feel free to release soon and tell @machinaeXlasse when you did so.

@machinaeXlasse when you got the new version, please test if the problem still persists for you. Dor me, at the current master, it does not. If you are happy with the result, feel free to close this ticket.

**Comment by desperateCoder** [comment]
Oh, i should also mention: as i tested it, i also tested the offline behaviour and found some issues, that are related to card- and label-handling. I fixed those on the fly. I hope it is quite solid now.

**Comment by stefan-niedermann** [comment]
`0.0.14` has been released. @machinaeXlasse please wait for the F-Droid-release (or build the master branch yourself). As @desperateCoder already mentioned: Just reopen this issue, if the problem still occurs.

Thank you.

**Comment by desperateCoder** [comment]
Dang... just happened again.

**Comment by desperateCoder** [comment]
@machinaeXlasse since this is a race condition, it's hard for me to tell if i'm just lucky or really fixed the issue. Please test it (current master, or just wait for the next release) and feel free to reopen this issue, if the problem still persists. I did a few tests and anything went well for me. Technically it should work well for all, but the machine is always right, so please tell me, if i'm wrong again :smile:
