### ISSUE TITLE
Render more markdown in description

### ISSUE THREAD

**Issue by reox** [stefan-niedermann/nextcloud-deck#311]
**Is your feature request related to a problem? Please describe.**
The webinterface is able to render some markdown, for example checkboxes in the form of `[ ]` and `[x]`. It would be very nice to see this function in the app too and be able to check the things in the comment.
So far, these markdown feature seems to be implemented in the webinterface:
* checkboxes via `[ ]` and `[x]`
* lists via `*`
* code via ``` (block) or ` for inline
* grey via `*this is grey*` or `_this is grey_` (I think it should be italic but somehow thats not implemented?)
* bold via `**this is bold**`
* headlines via # and ##
* strike through via `~~strike through~~`
* others I havn't found yet

The webinterface also counts the number of checked vs all checkboxes.

**Describe the solution you'd like**
* Render Markdown as in the webinterface
* Count the number of checkboxes

**Describe alternatives you've considered**
* Have a full rich text editor? Don't know if this makes sense on a mobile device though.

**Additional context**

**Comment by stefan-niedermann** [comment]
Thank you for the feedback 🙂.

Yes, this is absolutely valid. Though the comments will be readonly for a while (so no toggling checkboxes for now) because we are still using a buggy library.

<details>
<summary>Click here for technical details</summary>

We are currently using `RxMarkdown` for the description. We do this, because it is a fast lib and we are using it also in the Notes-app. But it has some major issues and is not maintained anymore.

The Notes-App is planning to switch to `Markwon` as a rendering library and if Notes is done, Deck will follow. After switching the lib, we can extend the support for toggling checkboxes pretty easy and do some other fancy stuff, but it does not make sense to implement this before we switched the lib.

Static rendering of the comments shouldn't be a problem though and i think this might be a quickwin for everyone.
</details>

**Comment by reox** [comment]
thanks for the feedback and technical description! 
I also noticed now, that several markdown elements do actually work already in the app.
So checkboxes and lists/enumerations seems to be the only things missing IMO

**Comment by stefan-niedermann** [comment]
Btw do you really refer to "comments" or to the "description" of the cards? (long term goal is of course to support both well)

**Comment by reox** [comment]
Oh, I did not even noticed that there is a different :man_facepalming: 
I actually mean the description! I'll change that in the first entry

**Comment by stefan-niedermann** [comment]
Closing this in favor of issue number 452 (Use Nextcloud Text for description for appropriate markdown rendering).

**Comment by stefan-niedermann** [comment]
Fixed in `1.13.1`.
