### ISSUE TITLE
Can't change order of cards

### ISSUE THREAD

**Issue by nr458h** [stefan-niedermann/nextcloud-deck#315]
I don't know if this is a bug or a feature request.

Expected behavior
When I take a card and place it at a different place in the same column I expect it to stay there

Actual behavior
When I move a card in the same column and update the board (with a pull down) the card is moved back to the previous position

**Comment by desperateCoder** [comment]
Bug. But a nasty one, because I can't reproduce it. When you have moved a card from position 1 to position 3, the first three cards should have a sync indicator (blue sync icon) at least for a second until the changes are synced. Can you confirm? If yes: do the indicators stay? If no: could you please provide a video? What app- and Deck-Server-Version do you have installed there?

**Comment by nr458h** [comment]
Sorry for not responding - somehow the problem disappeared without any change (or upgrade).
I will close here and if it reappears I will provide more information ;)
Thanks anyway

**Comment by desperateCoder** [comment]
Lol, weird. But hey! That's my favorite kind of bug ❤️ 

Glad, that it works for you! If not: reopen anytime!
