### ISSUE TITLE
Reenable server side reorder

### ISSUE THREAD

**Issue by desperateCoder** [stefan-niedermann/nextcloud-deck#360]
and implement onResponse()

**Comment by stefan-niedermann** [comment]
Since we will increase the min version of the android app, we should increase it to `1.0.0` directly (this way we can also remove the feature toggles for the comments). We therefore should wait with this feature until server `1.0.0` has been shipped for 2 months *and* we have to think about what we do with users who upgrade the android app but do not have an up to date server? block the app? just give a permanent hint? ...

**Comment by stefan-niedermann** [comment]
Screw it. Since we have to be offline capable, we need to reorder ourself anyway.
