### ISSUE TITLE
copy and share (internal) link to board or card

### ISSUE THREAD

**Issue by jakobroehrl** [stefan-niedermann/nextcloud-deck#497]
from nextcloud app:

![Screenshot_20200514-222154](https://user-images.githubusercontent.com/24530680/81982151-a4c29180-9631-11ea-9390-303eafa7a899.jpg)

**Comment by stefan-niedermann** [comment]
I will only implement "share" link to cards, because

- in recent android versions the share dialog also contains a "copy" entry
- an additional "copy" entry would need a separate item in the menu, and i want to keep it clear

**Comment by stefan-niedermann** [comment]
![image](https://user-images.githubusercontent.com/4741199/82142781-20455e00-983f-11ea-9a0e-4fb1f6dc15fd.png)

![image](https://user-images.githubusercontent.com/4741199/82142788-2f2c1080-983f-11ea-8994-2f1db306eb1d.png)

This function is only available beginning with verison `1.0.0` of the server because i am not sure if the URL changed while rewriting the app to `vue`.

**Comment by stefan-niedermann** [comment]
Will be in android app version `1.4.1`
