### ISSUE TITLE
Can't share board with some users (working on the server)

### ISSUE THREAD

**Issue by jakobroehrl** [stefan-niedermann/nextcloud-deck#510]
**Describe the bug**
In the app I can share a board only with a few users, other users aren't available.
On the server I can share the board with all users.

Server:
![grafik](https://user-images.githubusercontent.com/24530680/82647520-9c142180-9c16-11ea-9f4a-d3d2b220efd7.png)

- Device: tested on 3 different smartphones
- Android-Version: 8-10
- App-Store: Google Play Store App

**Comment by desperateCoder** [comment]
Hi @jakobroehrl,

please try the following:
* Web: share a board with a user not shown in android app
* Android: synchronize
* Android: create a board
*Android: try to share created board to the person in step 1
-> is the person shown?

I don't think this is a device-specific issue, i'd guess the app currently doesn't know the users, because in the data known to the app the specific user is never mentioned, so the app doesn't know the user yes, thus no suggestion

**Comment by stefan-niedermann** [comment]
@desperateCoder same as #492 ?

**Comment by jakobroehrl** [comment]
@desperateCoder Thanks, this is working.

**Comment by desperateCoder** [comment]
@jakobroehrl this is sort of a workaround then, but we should fetch all available users at some point. Guess I'll dig into this. Thanks for testing!

@stefan-niedermann don't think so, but can be implemented in the same scope.

**Comment by desperateCoder** [comment]
@stefan-niedermann i tested this, seems to work smoothly. Please test on your test-devices, too, then tell us, when this is going to make our users happy :grin:

**Comment by stefan-niedermann** [comment]
Will be published in version `1.6.0`

**Comment by stefan-niedermann** [comment]
@jakobroehrl since you are quiet active at the Deck server app: This implementation will cause pretty much network traffic and requires much performance.

I would really appreciate if you could prioritize the corresponding server issue for a better implementation high: https://github.com/nextcloud/deck/issues/2080

cc @juliushaertl

**Comment by stefan-niedermann** [comment]
Update: Sorry for the noise. See https://github.com/nextcloud/deck/issues/2080#issuecomment-650570516 (i think we won't need the new proposed API for a better implementation)
