### ISSUE TITLE
Card order not synced properly

### ISSUE THREAD

**Issue by thenickname** [stefan-niedermann/nextcloud-deck#524]
Card order is not synced when changing it in Android app. After interacting with the board through the web app, order syncing seems to start working in the Android app as well.

**To Reproduce**
1. Open Android app
2. Create new card(s)
2. Change card order
3. Notice that the sync icon that usually appears on the card does not appear
4. Refresh board
5. See how card positions change to their old state
6. Go to web app and reorder cards there
7. Go back to Android app, refresh board and reorder cards again
8. Notice how now the sync icon on the cards appears and order is properly synced

**Expected behavior**
Order is properly synced.

**Smartphone (please complete the following information):**
- Device: Xiaomi Mi Note 10
- Android-Version: 9
- App-Store:
  - [ ] Google Play Store
  - [x ] F-Droid

**Stacktrace**

**Comment by stefan-niedermann** [comment]
References https://github.com/stefan-niedermann/nextcloud-deck/issues/360

**Comment by JohannesStroebel** [comment]
I can confirm this bug. Xiaomi Mi 9t

**Comment by desperateCoder** [comment]
The issue was, that at card creation i didn't set the order properly, resulting in all cards having order 0. The reorder algorithm then saw that the new order is the same as the old one, so nothing to do here. 

Now we set the order at creation properly. Additionally the reorder will recognize broken orders and fix them automatically for you if needed.

Please tell us, if you still encounter some issues with that and thanks for this report @thenickname and @JohannesStroebel!

**Comment by desperateCoder** [comment]
Oh, one more thing: @stefan-niedermann told me we are going to ship this in the next version (1.5.1)
