### ISSUE TITLE
[New Design from Files App] Feedback

### ISSUE THREAD

**Issue by splitt3r** [stefan-niedermann/nextcloud-deck#575]
First i have to say that the new design looks damn amazing in all of the Nextcloud Android Apps ❤️. Thanks for the great work.

Two very small nitpicks:

| 1 | 2 |
| --- | --- |
| The account status icon is 🔵 in the Notes app but 🟢 in the Deck app. Is there a reason for it? ![image](https://user-images.githubusercontent.com/1869584/86272436-dd60ff00-bbce-11ea-8846-dd3fe2b66d77.png) | The second small thinng i noticed is that the sidebar has a wonderfull dark black color in the Notes app while it is a dark grey in the Deck app. ![image](https://user-images.githubusercontent.com/1869584/86272405-cf12e300-bbce-11ea-9fe3-229d37f98d7c.png) |

**Comment by stefan-niedermann** [comment]
Thank you for the feedback :heart: 

> The account status icon is 🔵 in the Notes app but :green_circle:  in the Deck app. Is there a reason for it?

Yes. **Notes** is a bit further in matters of branding and uses the instance **color of the account** (by default "Nextcloud"-blue) to color the check icon.
Since we are using the **color of the board** as branding color in the **Deck** app (because it provides a better context), this will be eventually the color of the checked-circle-icon. It is a bit tricky to deal with those kind of graphics because we are dynamically generating them.

As a quick win i changed the color to default "Nextcloud"-blue

> The second small thinng i noticed is that the sidebar has a wonderfull dark black color in the Notes app while it is a dark grey in the Deck app.

Will have a look into this :)

**Comment by stefan-niedermann** [comment]
Updated APK: https://github.com/stefan-niedermann/nextcloud-deck/suites/865220878/artifacts/10003874

**Comment by AndyScherzinger** [comment]
@stefan-niedermann fyi https://github.com/nextcloud/server/issues/21586#issuecomment-650045835 - we'll improve dark/light color calculations on the server-side and will add this to the files app as soon as it becomes available (with fallbacks of course) with Nc server 19.0.1

**Comment by stefan-niedermann** [comment]
Thanks for the hint.

Deck app only uses the color of the boars, notes app uses only the main color of the account.

We do not use the `text color` anywhere, but calculate it ourself depending on where we need light / dark colors.

Where do you think this could be relevant?

**Comment by AndyScherzinger** [comment]
Well, since you seem to not use the primary color, probably not. Maybe for the notes app then 🤔
