### ISSUE TITLE
View mode for the card deck note field

### ISSUE THREAD

**Issue by armaccloud** [stefan-niedermann/nextcloud-deck#606]
**Is your feature request related to a problem? Please describe.**
Whenever I want to tick off a task in one of my cards (tickbox), I have to place an X into the markup in the note field.
When I want to read a text in the card, it contains markup formatting which looks untidy in such a small small text box.

**Describe the solution you'd like**
It would be great if the note field would open in a view mode (where you can tick a tickbox) and have the option for edit mode when it is necessary.

**Comment by stefan-niedermann** [comment]
Hi @armaccloud 

While I absolutely understand your struggle, we will unfortunately not do this (at this point).

We plan to move to [Nextcloud Text](https://github.com/nextcloud/text) as Markdown editor in the long term (https://github.com/stefan-niedermann/nextcloud-deck/issues/452) and we will not put any effort in [the current Markdown editor](https://github.com/yydcdut/RxMarkdown/). It is buggy and not maintained.
We did this very mistake in the [Notes app](https://github.com/stefan-niedermann/nextcloud-notes/), and now have some kind of lock-in there. This results in not being able to easily switch to any other library there because we have millions of workarounds and different parts of the app.

I'd like to avoid this really bad situation at the Deck app and hope you can understand the reasons and be a little more patient until someone grabs #452.

**Comment by armaccloud** [comment]
@stefan-niedermann I understand it's much better to have a well-designed solution instead of a buggy one.  I will wait patiently for #452
