### ISSUE TITLE
Release as Viewer App

### ISSUE THREAD

**Issue by timkittel** [stefan-niedermann/nextcloud-deck#65]
Hi,
what are the last necessary steps/issues until this App can be released (on F-Droid?) as a Viewer App? And any recommendations where help would be appreciated?
Best,
Tim

**Comment by stefan-niedermann** [comment]
I will have a talk with the other developers and evaluate if we want to do that (we would need to remove some functionality and maintain those changes).

I will post a roadmap in the README when we came to a conclusion.

Help would be appreciated in each open issue, especially in Drag'n'Drop cards accross stacks - this feature is essential IMHO, even for a "viewer"-release.

For the frontend part: just open a PR. If it works, we can merge it.

For the backend part: please contact @desperateCoder because he is doing heavy black magic with the persistence and snychronisation ;-)

**Comment by desperateCoder** [comment]
I'd even pitch just releasing it as it is, since the current state is already all functional for viewing cards. The half-way implemented features don't break anything, and if they do, just reinstall the app. The black voodoo stuff I am currently working on is the sync from client to server, which has no impact on the viewing functionality, there is already some other voodoo implemented for that. 

Just tag the current version and feel free to release it on F-Droid (but not play store!) For all the masochistic folks out there.

If you really want to help, install the app and do some dogfooding :grin:

**Comment by timkittel** [comment]
> I will have a talk with the other developers and evaluate if we want to do that (we would need to remove some functionality and maintain those changes).

That sounds like a lot of work. Hence, I really like @desperateCoder's suggestion of releasing it (more or less) as is. I think the only thing one might add would be short messages when things do not work, e.g. that a change to card is currently not saved and reverted when the app synchronizes the next time.

> If you really want to help, install the app and do some dogfooding :grin:

doing that already (:

**Comment by iSpeeX** [comment]
Hello,
I'm wandering how can I install the apk to test it and help as much as I can. Can someone help me with this ?

By the way : keep up the good work, you guys are really good !

**Comment by stefan-niedermann** [comment]
Thank you :) We are working on a first alpha F-Droid release. A Play Store release will still take some time, as we only want to release a productively usable version on Play Store.

You can grab any issue, ideally one labled as "good first issue" or "help wanted" and start a PR. :rocket"

**Comment by desperateCoder** [comment]
Thanks @iSpeeX, glad to hear that!

Currently the app is under heavy development, so there isn't really an APK we would safely release for users. As a developer you can just clone our repo, build the app via Android Studio and start testing and contributing as @stefan-niedermann said. 

Did this help you?

**Comment by iSpeeX** [comment]
Well, I'm not a developer... I mean, I'm more into Systems/Networks/Management, but I'll take a look on Android Studio !
You helped me a lot, I know how to get the apk from Android Studio so i'll give it a try soon.

Thank you guys

**Comment by desperateCoder** [comment]
Please note, that the currently released server app isn't compatible, you will have to install at least the beta version mentioned in the readme file. The release of the beta version may take some days to weeks.

**Comment by stefan-niedermann** [comment]
Good news, folks: I recently opened a request to add this app to the F-Droid-Repository: https://gitlab.com/fdroid/fdroiddata/issues/1613

**Important**: This app is still under heavy development, it might break with each new version and writing access is not possible / might cause problems or lead to data loss. So be careful and do not use it productively!!
