### ISSUE TITLE
Recognize + [ ] syntax for task counter

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#652]
[corresponding server issue](https://github.com/nextcloud/deck/issues/2187#event-3646044737)

**Currently recognized syntax:**

```md
- [ ]
* [ ]
```
**To add:**

```md
+ [ ]
```

**Comment by stefan-niedermann** [comment]
Maybe we should use the same regex as the server for feature parity (or provide a PR for the server to adapt our solution?)

**Comment by desperateCoder** [comment]
Dug into this, the current regex is valid, since there is no opening `[` to the last closing `]`. But anyways, if you ask me, you can simply close this, since we already find those checkboxes, regardless the listing char. I'd expect id just like it is.

Do you think there is more to do @stefan-niedermann?
