### ISSUE TITLE
Add "Upcoming cards" board to mobile app

### ISSUE THREAD

**Issue by aproposnix** [stefan-niedermann/nextcloud-deck#690]
**Describe the solution you'd like**
Add the "Upcoming cards" board to the mobile app. So when the user opens the blade menu, they will see it listed as the first board in the board list.

**Comment by stefan-niedermann** [comment]
I am not 100% sure about this feature. I think this is a better use case for a widget instead of the app itself - (and will be covered by #597 in this case. The server app doesn't have this possibility, but on the Android platform i'd rather think that this should be handeled by a widget - open for other opinions, though :)

**Comment by aproposnix** [comment]
@stefan-niedermann Yeah, I think a widget could do the trick. Basically it would be an agenda view that would show all upcoming tasks + past due.

**Comment by stefan-niedermann** [comment]
So after getting a :+1: and also you agreed @aproposnix :

Let's go for the #597 Filter widget to cover this use case instead of implementing it directly into the app itself. :slightly_smiling_face:

**Comment by q-wertz** [comment]
Sorry to post in an old issue but I didn't want to open a new one as this is more of a discussion.

I think having the upcoming cards view also in the app would be quite nice.
1. The user experience is then similar to the one in the browser
2. I was looking 100 times for it in the app (because I read about it in the changelog) until I understood that it is a widget ( I think more people have the same problem https://github.com/stefan-niedermann/nextcloud-deck/issues/838 which maybe shows the request for/interest in/potential of this feature)
3. Personally I am not a big supporter of too many widgets. They just take too much space on the homescreen. I already have my Calendar and Task widgets and the one of Deck is kind of specific for this application

**Comment by stefan-niedermann** [comment]
I agree, we should add an upcoming cards view to the app as well.

**Comment by stefan-niedermann** [comment]
Will soon be published with `1.17.0`.
