### ISSUE TITLE
Sync on app start

### ISSUE THREAD

**Issue by jakobroehrl** [stefan-niedermann/nextcloud-deck#709]
If I open the app, the cards are not up to date because I changed something on other devices. 
Maybe it would be nice to do a auto sync if the app was opened (like on the notes app)

**Comment by desperateCoder** [comment]
Uhm....it actually should behave like this.... @stefan-niedermann ? Something I'm not aware of? 

@jakobroehrl maybe you're on mobile data and set the app to "only sync on WiFi"?

**Comment by jakobroehrl** [comment]
No, mobile data are actived. 
Maybe the auto start sync is running always into this: https://github.com/stefan-niedermann/nextcloud-deck/issues/680

**Comment by stefan-niedermann** [comment]
Yes, it should already auto-sync on start.
Maybe this is related to #680 
Notice, that at the start-up sync the sync animation is not shown (by intention)
@jakobroehrl you are aware that due to the lack of `ETag` support of the server app a synchronization can easily take up one minute (or even more, depending on the amount of data)? Have you already tried to be "patient"? 😉

**Comment by jakobroehrl** [comment]
I waited 5 mins. 
I only have 60 cards in 10 boards.
So it must be https://github.com/stefan-niedermann/nextcloud-deck/issues/680
Is there a way to solve So it must be https://github.com/stefan-niedermann/nextcloud-deck/issues/680 soon?

**Comment by stefan-niedermann** [comment]
As commented in #680 this is not easy to debug. I still think the best chance to stabilze the sync is `ETag` support. And there we rely on the server app. So no, i don't see any shortcut here, but i am open for ideas 🙂
