### ISSUE TITLE
Archive lists

### ISSUE THREAD

**Issue by Jeanoo** [stefan-niedermann/nextcloud-deck#725]
Suggestion 
If I understand the purpose of archiving cards is to make room for all the cards to be clearly visible.
Then I don't understand why the lists were not archived at the same time as the maps?

**Comment by stefan-niedermann** [comment]
Because lists are meant to be a way to describe a kind of workflow for cards, like `ToDo` → `Work in Progress` → `Done`.
The cards should move from the left to the right within their lifecycle. Since the lists (= "states") are static in this scenario, they don't disappear when archiving all the cards of a list. The lists are the same for future cards which will be dragged there.

(At least that's how it is supposed to be - it can be used in any wy that is good for *your* needs).

**Comment by stefan-niedermann** [comment]
PS.: As you wrote "suggestion", i have to say, that we follow the server app. If you propose to change this behavior, you need to ask [in the repository of the server app](https://github.com/nextcloud/deck/issues/new?template=Feature_request.md).

**Comment by Jeanoo** [comment]
Thank you Stefan, I have created a message here https://github.com/nextcloud/deck/issues/2530
