### ISSUE TITLE
Refresh problem

### ISSUE THREAD

**Issue by kai11** [stefan-niedermann/nextcloud-deck#75]
I've compiled master branch and tested it on my phone with 2 nextcloud decks I'm working with.

**To Reproduce**
1. Add account
2. Decks fetched, but not columns and not tasks.
3. Wait some time (I had to wait one day once). 
4. Add new column via web and new card.
5. Even after some waiting and refreshing, I don't see new columns and new cards.

Closing and opening app don't help.
Refresh gesture (scroll down) don't help.
Switching between accounts don't help.

**Expected behavior**
Refresh should fetch latest data 

Is there any way I can do force-refresh in current version?
I think this is required even for viewer app without full editing.

**Comment by desperateCoder** [comment]
Hi @kai11,
thanks for testing our App :smiley: !
To me it looks like you aren't at the latest server(!) deck app. As stated in the Readme, it should be at least version 0.6.1 or later, the later the better.

The server app had to be changed to provide more date for our app, so it seems the app is expecting some data it doesn't get and crashes.

If you verify your server-deck-app version and the problem still persists, please provide a stacktrace, since it seems you have an Android Studio running, you can get it out of the "Logcat" view.

Thanks in advance!

**Comment by kai11** [comment]
Server version upgrade fixed this problem.
I had one server on 0.6.1 and another on 0.5.2 and second one was selected by default.

**Comment by kai11** [comment]
Actually it may be confusing for new users who simply forgot to update.
Maybe it should be a message or toast or notification?

**Comment by desperateCoder** [comment]
@kai11 You are totally right! @stefan-niedermann? Go for it!

**Comment by desperateCoder** [comment]
This feature can be implemented, as soon as we have a dev build of https://github.com/nextcloud/deck/pull/1047 

@juliushaertl thanks for that, hope it is going to be released soon

**Comment by tobiasKaminsky** [comment]
Actually you can already built it in, assuming that if you do not get a proper value for this capability, you are < 0.6.1.

**Comment by desperateCoder** [comment]
@tobiasKaminsky You are... Kinda... Right... Admit! The devil told you!

**Comment by desperateCoder** [comment]
@tobiasKaminsky the current version is 0.6.1, the version will be available at the next release I guess?? So the current version is already compatible, but I won't get a version, right? So there still might be a problem, right?

**Comment by tobiasKaminsky** [comment]
Hm. Did not knew that 0.6.1 is compatible.
Maybe Julius can do a 0.6.2 soon which would solve it.

**Comment by desperateCoder** [comment]
@tobiasKaminsky maybe we could just display a warning that it _might_ be an incompatible version and make the user double-check that, in case he doesn't get stacks...

**Comment by tobiasKaminsky** [comment]
If you do not have a version string and show instead a "might be possible too old server" is also good :-D

**Comment by juliushaertl** [comment]
Yes, a 0.6.2 is waiting to be released. I'll make sure to include the capability entry in that.

**Comment by TobiasDev** [comment]
Hello! I also see this issue that my data isn't refreshed.

I'm on latest deck for NC and I'm using the app from F-Droid (so not sure if I should report it yet or not?). :)

**Comment by desperateCoder** [comment]
Hi @TobiasDev,
Thank you for your report!
We are aware of these problems and are currently about to resolve them. 

Please be patient and wait for the next update via f-droid, if the problems still persists for you, please open a new issue then.

**Comment by stefan-niedermann** [comment]
The latest master checks for the minimal version (currently 0.6.4) and displays an error message with the option to directly upgrade your deck app version in your nextcloud instance.

please open a new issue if you notice any further issues :)

PS.: F-Droid updates will take some time because we did not tag this version yet. Stay patient in this case :)

**Comment by desperateCoder** [comment]
In addition: there were a bunch of improvements since the last version, hope you guys will enjoy them!
