### ISSUE TITLE
Create push notifications when card expiry date/time expires

### ISSUE THREAD

**Issue by Luke1982** [stefan-niedermann/nextcloud-deck#779]
I love the Android App, but it would be very nice if there was a push notification when a card expiration date/time is met or almost met.

**Comment by desperateCoder** [comment]
Hi @Luke1982,

In fact this should already be working, if you have play services installed. The push notifications will pop up via the nextcloud files app. If you have play services enabled, please check your notification settings in Android. You could also check. If the server app has some settings for that. I get plenty of notifications via push.

**Comment by Luke1982** [comment]
I have the nextcloud files app (with that I mean the nextcloud main app), but I don't know what you mean by the play services. Is that an app? My nextcloud app says 'notifications are not available'

**Comment by stefan-niedermann** [comment]
> with that I mean the nextcloud main app

Correctly 👍 

If you have installed a custom ROM or did some advanced modding on your phone **or** if you have a new Huawei device, it might be possible, that you are lacking Play Services (it's some proprietary stuff from Google to enable battery optimized push notifications).

> My nextcloud app says 'notifications are not available'

In this case, the Deck app of course doesn't receive push notifications also, because we use the feature from the files app.
You should open an issue [over at their repository](https://github.com/nextcloud/android/issues/new?labels=bug&template=bug_report.md) because there is unfortunately nothing we can do, if it doesn't work with the files app.

**Comment by Luke1982** [comment]
I have a fairphone 3 which, as I recall is very close to stock android and I installed the app through the play store. I think I do have play services. Will check with the nextcloud people

**Comment by stefan-niedermann** [comment]
Yes, when you got your apps from the Play Store, you actually **have** Play Services. In this case this might be really a bug in the Nextcloud app. Would be great if you could link your issue from the files app here and notify us about the progress 🙂 ?

**Comment by Luke1982** [comment]
I think it is the NC app version, as you can see [here](https://github.com/nextcloud/android/issues/7567). Don't want to create duplicate issues

**Comment by desperateCoder** [comment]
Thanks for the feedback! Now we know what's happening, in case we get more bug reports like yours.
