### ISSUE TITLE
Most Android app actions duplicated on server

### ISSUE THREAD

**Issue by bnjbvr** [stefan-niedermann/nextcloud-deck#795]
**Describe the bug**

It happened to me that adding a card to a list (in a given project) would sometimes create duplicates of the same card, when refreshing on the android app (and as confirmed by looking at the web app). Today, something a bit worse happened: I've created a new project and it was duplicated; then in the new project I've created new lists, and two out of them were duplicated as well. So it seems there's something generally wrong with the synchronization, resulting to some actions seemingly triggered several times. It might be intermittent too because sometimes adding a card just works fine.

**To reproduce**
Issue is reproducible with an account from [try.nextcloud.com](https://try.nextcloud.com):
- [ ] Yes
- [ ] No
- [x] No idea

1. Create a new project / list / card.
2. Refresh content of the app (e.g. close and re-open the app, without forcing closure).
3. Observe duplicated content.

**Expected behavior**

Nothing duplicated

**Screenshots**

(None, as I've removed the duplicate entities in the meanwhile :-/)

**Versions**
 - Nextcloud: 20.0.4
 - Nextcloud Deck: 1.2.3
 - Nextcloud Android: 3.14.1
 - Nextcloud Android Deck: 1.13.4

**Smartphone (please complete the following information):**
- Device: S20+
- Android-Version: 11
- App-Store:
  - [x] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [ ] Huawei AppGallery

**Are you using LDAP?**
- [ ] Yes
- [x] No

**Stacktrace**

None

**Gratitude**

Thanks for making this app! this small bug really is just a minor nuisance, your app is really cool!

**Comment by desperateCoder** [comment]
Hi @bnjbvr,
thanks for your report! And big sorry for the inconveniences! To be honest, none of our users reported anything like that, but we'll have a look at this for sure! 

This sounds really odd, the sync is mostly my code and I can't really explain how this can actually happen... Are you a new user or do you use Deck for Android for a long time and are experiencing this behavior for the first time? Were you on mobile data or WiFi as this happened? Or maybe offline (we should support that as well)? Any hint would help now, since I'm quite clueless how this could even happen...

**Comment by bnjbvr** [comment]
No worries! I'm a recurring user, and I've observed this when I've started using Deck (around 6 months ago), and again just today. So it doesn't seem to happen 100% of the time, for some reason, it's intermittent. Both instances I was using WiFi and wasn't offline. I'll try to gather logs or something, the next time this happens!

**Comment by desperateCoder** [comment]
> I'll try to gather logs or something, the next time this happens!

Aw, that'd be great! In the meantime I'll try to reproduce that as well.

**Comment by stefan-niedermann** [comment]
@bnjbvr have you been able to fetch any logs in the meantime?

**Comment by bnjbvr** [comment]
I use Deck a bit less frequently because of this particular issue, and I haven't retriggered it since this bug report. So, no -- sorry it's not a very helpful response.

**Comment by stefan-niedermann** [comment]
No problem. Since we aren't able to reproduce the issue and are quite blind without any logs, i propose to close this issue until we have further information. I literally have no clue how we should find the root cause, especially since this seems to affect no other user.
Is this fine for you @bnjbvr ?
Maybe you can also verify whether this behavior happens for you on another instance (there are various free instances available at the [simple sign-up program](https://nextcloud.com/signup/)) when you have a bit time.
Of course you can reopen the issue at any time, when you have more information :slightly_smiling_face:

**Comment by bnjbvr** [comment]
Yes, sure! I'll let you know if this happens again in the future!
