### ISSUE TITLE
Left menu empty after the startup

### ISSUE THREAD

**Issue by lachmanfrantisek** [stefan-niedermann/nextcloud-deck#80]
**Describe the bug**

After the start of the app (fdroid 0.0.2) I do not have any accounts (see #78 ).

When I wanted to add a new account by hand I did not know on what I need to click.  The  left menu is empty and it took me a while to click on the top text.

**To Reproduce**
1. Open the left menu when having no accounts.
2. The menu is empty.
3. To add a new account I need to click on the top text.

**Expected behavior**

I am not sure how it looks when having some account, but when having no accounts I would like to have a `add a new account` option in the left menu.

The app should look good and intuitive also when having no account.

**Screenshots**

![Screenshot_2019-05-16-07-23-21-632_it niedermann nextcloud deck](https://user-images.githubusercontent.com/20214043/57835576-1d90d280-77bf-11e9-91be-84d25e07de21.png)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi4c
 - Android-Version: 7

Thanks!

**Comment by tobiasKaminsky** [comment]
There should be an "arrow down" to indicate that the list can be switched:
![2019-05-16-095448](https://user-images.githubusercontent.com/5836855/57836298-ad834c00-77c0-11e9-881c-b929bbad6750.png)

Also if there is no account yet, it should directly show "add account" functionality

**Comment by lachmanfrantisek** [comment]
Thanks for the clarification. I know the behaviour from Files app (like your screenshot), but I was just confused that there is nothing in the menu and no button to add an account. (And the `show "add account" functionality` was not raised due to #78 )

**Comment by stefan-niedermann** [comment]
@TobiasKaminsky the arrow should be there, but @AndyScherziger mentioned there is a bug which prevents the arrow to be displayed.

However: 1. The whole area is clickable

2. This issue might get solved automatically - We will not allow the app to be used without a valid account (and yes, we aim to support the Dev-Version of the files app)

3. SSO will stay the only way to authenticate due to many reasons (Networkstack, 2FA and many others)

Stay tuned for updates :)

**Comment by lachmanfrantisek** [comment]
Thanks for the info. If you think this issue is not needed, feel free to close it.
