### ISSUE TITLE
not all cards from nextcloud deck show up in the app

### ISSUE THREAD

**Issue by drs-project** [stefan-niedermann/nextcloud-deck#829]
I like the deck app very much, but I just noticed that some cards are missing in the app.
I run the latest deck app in nextcloud with several boards. In one of them two cards don't get synced to the app on my android phone, despite all filters beeing disabled. I can't really see a difference to the other cards. 
Pulling down (reloading) in the app doesn't change the situation.

Please give me a hint what debug info would be helpful for you. I'll happy to provide it, if I can.

**Comment by desperateCoder** [comment]
Hi @drs-project, thanks for your report!

Next time, please fill out the issue template, it's there for a [reason](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#why-has-my-bug-report-been-closed).

We talked about this and came to the conclusion, that it might be a synchronization issue, so please try the following:
* Open one of the missing cards and change something - maybe the title or description, doesn't really matter
* Then perform a sync in the Android app.
* did the missing card appear?

Thanks in advance!

**Comment by drs-project** [comment]
Yes, after changing one card in nextcloud both missing cards showed up in app.
There is no related message in the nextcloud or apache logs.

**Comment by stefan-niedermann** [comment]
@desperateCoder `ETag`s?

**Comment by desperateCoder** [comment]
@stefan-niedermann Most likely. Not sure what caused this and no idea how to reproduce that behavior... It's even possible, that this is a server issue (not updated the Etag on card creation). Or. If the app is killed mid-sync the stack is updated but the cards are not. At the next sync the whole sta k is ignored because of the Etag match. 

I don't see any elegant way to solve this. Maybe we need something like "force a full sync"?

**Comment by chaosjug** [comment]
We seem to have the same (similar?) problem. Android app on two phones, both from fdroid. We usually add/change cards only in the android apps and often quite syncing does not work. The cards appear on the server but are not synced to the other phone. Pulling down just circles forever but does not do anything. Also changing something in the android app does not seem to have an effect. After reading this thread I changed a card in the web app and immediately everything got synced. Maybe this Etag thing is not reliably updated when the android app changes something?

**Comment by christianlupus** [comment]
I have seen the same problem. I "fixed" by unregistering the account in the deck app and re-registering it. I suspect this will remove any cached ETags, right?


> It's even possible, that this is a server issue (not updated the Etag on card creation).

One thing, I can definitively say is that it happened also for changing cards. So, I had a card in one stack and moved the card to another stack. In the android app, the card refused to move to the new stack. Had to recouple the accounts.

> I don't see any elegant way to solve this. Maybe we need something like "force a full sync"?

The problem is that the user is not aware of the problem. Only by chance, I saw it as I changed something on the laptop and 5 min later I had only my mobile phone at hand. So I knew I had done the change.

Is it possible to tap into the internals of the app (USB debugging) or is a dedicated installation required? In the latter case, how would one do this?
I am thinking in this direction: Prepare for USB debugging, keep using the app as usual. Once the problem manifests again, I could look at the cached ETags in the app and comparte with the ETags on the server/web version.

**Comment by stefan-niedermann** [comment]
> Maybe we need something like "force a full sync"?

Recent versions have a `Use ETags` option in the settings. Disabling it will not make use of `ETags` which is basically a " forced full sync". This is meant as workaround and not as solution.
You can try to disable the option for one sync and have a look whether this missing stuff appears and tell us, so we know that it is really caused by the `ETags`.

> Is it possible to tap into the internals of the app (USB debugging) or is a dedicated installation required? In the latter case, how would one do this?

It is possible, though you would need to install Android Studio to debug there. **What we really need is a was to reproduce this behavior reliably**, otherwise you will probably not find what you ware looking for.

**Comment by stefan-niedermann** [comment]
@drs-project @chaosjug are you able to reproduce this behavior in the latest released version (`1.18.2` or higher)? We did a bunch of enhancements to ensure that this *should*™ not happen again. Otherwise, please give feedback whether or not temporarily disabling `ETags` in the settings will make the missing cards show up?

**Comment by drs-project** [comment]
Haven't seen missing cards since the last upgrade to 1.18.2 from fdroid.
I just tried to reproduce the error but I couldn't - with or without Etags enabled.
Seems like you fixed it - great work and thanks a lot!
