### ISSUE TITLE
Add options to attached image for downloading and sharing

### ISSUE THREAD

**Issue by tigexplorer** [stefan-niedermann/nextcloud-deck#836]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**

If one like to share a attached image, one have to do many additional steps for login, downloading, select the image local and sharing it.

For an attached image, in the options dialog, one can get the url to the image. 
It may be very usefull to have also the option for downloading and sharing the image directly from within the app.

**Describe the solution you'd like**

In a card, tab attachments, tab attached image long, select option for downloading or sharing.

**Describe alternatives you've considered**

**Additional context**

**Comment by stefan-niedermann** [comment]
Starting with the deck server version `1.3.0` new attachments are stored as usual files within the Nextcloud account (there will be a [migration step](https://github.com/nextcloud/deck/issues/2698) for old attachments in a future release).

The Deck Android app already features a nice integration since `1.15.5` and supports those kind of new attachments: A click will directly open the file in the Nextcloud Android app. From there one has all file related actions like downloading and sharing by link and with other users.

Implementing this in the Deck app directly was a good idea before we had this kind of integration, but now it is just doubled functionality and we therefore don't plan to implement this in the Deck Android app anymore.
