### ISSUE TITLE
Unable to create a new deck

### ISSUE THREAD

**Issue by tubia** [stefan-niedermann/nextcloud-deck#87]
**Describe the bug**
When I try to add a new deck, a java error is shown.

**To Reproduce**
1. Open the left sidebar
2. Click on 'add deck'
3. In the popup, select color and name and click 'create'
4. In the main window you see

```java
it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$createBoard$2$SyncManager(SyncManager.java:170)
it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$3P2D-7BtdnPRYG9owpMOaZIALHA.run(Unknown Source:8)
java.lang.Thread.run(Thread.java:764)
```

**Expected behavior**
Create a new deck

**Screenshots**
No screenshots.

**Smartphone (please complete the following information):**
 - Device: zenphone 3
 - Android-Version: 8

**Stacktrace**
//

**Comment by desperateCoder** [comment]
Hi @tubia, 
thanks for your report!

I just tried it myself and had no problem at all.

Unfortunately i can't tell what`s wrong by the data you provided, since the code does'nt match with the stack above (some development has happened since your version, but not affecting the code in your stacktrace)

To be able to help you, i'd need the following information:
* Which version of the Deck-Server-Plugin do you use?
* Which version of our Deck-App do you use? (self-compiled at commit XY? F-Droid 0.2.0?)
* The _full_ stacktrace, since i don't even know what kind of Exception was thrown.

Did the Exception-dialogue come up after the app crashed? If it did, please provoke the crash again and copy the _whole_ message into a comment, so i have way better chances to find this nasty little bug for you and hunt it down until it never can bother any user ever again! Just kidding :yum:  but i'd like to fix this.

**Comment by desperateCoder** [comment]
@tubia I just realized, that the provided stacktrace might be all you got in the Exception dialogue, right?

Sorry for that, i fixed it in commit 4d7f5e6dae86b2481f8cbae1d3b5c3fd4ecf9e34

Do you have Android Studio running? The logs should display the whole exception, just as the next release will.

**Comment by denis-pujdak-adm-it** [comment]
I got the following error:
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Long it.niedermann.nextcloud.deck.model.User.getLocalId()' on a null object reference
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$createBoard$2$SyncManager(SyncManager.java:170)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$3P2D-7BtdnPRYG9owpMOaZIALHA.run(Unknown Source:8)
	at java.lang.Thread.run(Thread.java:764)

**Comment by stefan-niedermann** [comment]
Can you please both check if this problem still persists? We had a lot of changes in the "create board"-section of the code ;)

**Comment by stefan-niedermann** [comment]
Feel free to open a new issue if the problem still occurs. The next version should be available on F-Droid in a few days or you can compile the current master.
