### ISSUE TITLE
add new card button disappears when scrolling in a long board

### ISSUE THREAD

**Issue by piratenpanda** [stefan-niedermann/nextcloud-deck#913]
**Describe the bug**

1. Have a board with as many items so that a scrollbar is needed
2. scroll to the bottom
3. blue "+" button overlay disappears
4. scroll up and it reappears

**Expected behavior**
"Add new item" button should be visible all the time

**Versions**
 - Nextcloud: 21.0
 - Nextcloud Deck:  1.3.1
 - Nextcloud Android: 3.15.2
 - Nextcloud Android Deck: 1.15.5

**Smartphone (please complete the following information):**
- Device: Pixel 5
- Android-Version: 11
- App-Store:
  - [x] Google Play Store

**Comment by stefan-niedermann** [comment]
Dear @piratenpanda,

thank you for the request and especially for filling out the complete issue template.

The described behavior is considered to be a feature, not a bug. The problem with Floating Action Buttons from a UX perspective is, that it hides content and draws a lot of attention to it (making it hard to focus on the actual content). When someone is scrolling down a list, we assume that people are looking for something. In this situation, the content is more important than the create action (which is still reachable quite quickly).
Therefore we decided to follow the common pattern¹ of showing / hiding the Floating Action Button when scrolling. Since we are also a pretty small development team, we heavily rely on the input and help of the Nextcloud GmbH designers which recommend this behavior and also use this in their official apps besides to well known other apps which implement it this way².

Have a nice weekend and happy easter :slightly_smiling_face:

¹ Some UX resources recommending the current implementation:

- [uxplanet.org](https://uxplanet.org/floating-action-button-in-ux-design-7dd06e49144e#d426)
- [dreamerux.com](https://www.dreamerux.com/articles/c9jw77yllyelddl34ndgxrzc2sjzm8)
- [babich.biz/fab](http://babich.biz/fab/#fabcanbehiddenduringscrolling)
- [ux.stackexchange.com](https://ux.stackexchange.com/a/67445)

² Some reference apps which also implement this behavior:

- [Nextcloud](https://play.google.com/store/apps/details?id=com.nextcloud.client) (Nextcloud GmbH)
- [Nextcloud Talk](https://play.google.com/store/apps/details?id=com.nextcloud.talk2) (Nextcloud GmbH)
- [Nextcloud Notes](https://play.google.com/store/apps/details?id=it.niedermann.owncloud.notes)
- [Telegram](https://play.google.com/store/apps/details?id=org.telegram.messenger)

**Comment by TtuxX** [comment]
Hello @stefan-niedermann! :)

I hope you are well and I wish you, your friends and family a happy new year! :)

I have a bit of this problem, because when I add a card, the FAB button disappears until I manually refresh the tab, or switch to another one and back to the one I was working on.

Is this also an expected behaviour?

Thank you very much in advance.
