### ISSUE TITLE
When multiple notifications are shown, only the first card can be opened

### ISSUE THREAD

**Issue by af7567** [stefan-niedermann/nextcloud-deck#952]
**Describe the bug**
When cards have a Due date and time set, a notification will be shown at the specified time. If more than 1 of these notifications is displayed then only the first card can be viewed whichever notification is tapped.

For example card1 has a time of 15:00, and card2 has a time of 15:10.
At 15:30 we will have 2 notifications - one for card1 and one for card2.
Tapping the card2 notification will open up card1 in the Deck app.
The card1 notification will remain, and tapping on that will now do nothing except dismiss the notification.

**Expected behavior**
Tapping card2 should give the option to open card2. Then tapping card1 should give the option to open card1

**Versions**
 - Nextcloud: 21.0.1
 - Nextcloud Deck: 1.4.1
 - Nextcloud Android: 3.16.0 RC2
 - Nextcloud Android Deck: 1.18.2 (also tested with 1.17.7)

**Smartphone (please complete the following information):**
- Device: Google Pixel 3a
- Android-Version: 11
- App-Store: F-Droid for version 1.17.7. 1.18.2 compiled myself.

**Comment by stefan-niedermann** [comment]
Well, i guess this has to be fixed on the Nextcloud Android apps side.

Notifications are fetched *and* displayed by the Nextcloud Android app and only after tapping on it, the Deck Android app comes into the game. Since a tap starts an Intent to open the Deck app, i guess that the mapping of notifications to the Intents in the Nextcloud Android app is wrong.

Closing this, because from my point of view the issue cannot be handeled here - But since you compiled the Deck app yourself, you are apparently a developer? Maybe you could have a look into the integration yourself?
A good starting point will be [here](https://github.com/nextcloud/android/blob/master/src/main/java/com/nextcloud/client/integrations/deck/DeckApiImpl.java) 🙂.
