### ISSUE TITLE
Unable to create cardds

### ISSUE THREAD

**Issue by gerhardbeck** [stefan-niedermann/nextcloud-deck#96]
**Describe the bug**
Unfortunately I'm unable to create cards: When trying to add a new Card on + there is no "save" button. When moving back it didn't save
Same problem when trying to change an existing card
Boards work.

**To Reproduce**
1. Go to '+'
2. write anything
3. no saving

**Expected behavior**
whether a button "save" or saving then clicking "back"

**Smartphone (please complete the following information):**
 - Device: Nokia 5
 - Android-Version: 9

**Stacktrace**
Please provide a stacktrace when possible.

**Comment by desperateCoder** [comment]
Hi @gerhardbeck,
since we are in alpha stadium, not all features are ready yet. We stated it in any readme you can find: the current state is a pure viewer app and it is far from perfect even for this purpose. :smile: 

We do our best, but please be patient, since we are working on this app in our spare time. Just trust me, one day this will work, too.

**Comment by gerhardbeck** [comment]
@desperateCoder Well, I think you're much better than a viewer app as one can add boards. Therefore I thought it is a bug...
I love the app, even in alpha state...

**Comment by desperateCoder** [comment]
Glad to hear that! We will add that for sure! The "Kuddelmuddel" of the features is because we didn't plan to release it before having a stable editor app, but the pressure and interest of the users was very high, so some edit features implemented before are still available. 

A good friend of mine would also love this feature, so I hope @stefan-niedermann will find some time to implement this soon!

**Comment by stefan-niedermann** [comment]
I would say, we can close this issue in favor of #41 since this is a duplicate :)
