### ISSUE TITLE
Improve 'Move Card' Dialog

### ISSUE THREAD

**Issue by newhinton** [stefan-niedermann/nextcloud-deck#972]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

The current dialog shows three picker immediately:
 - Account
 - Board
 - List

I think this could be improved by beeing aware where the user is:
Immediately show a list of 'Lists' and when clicking on one, move the card there. 

However, to still allow moving between accounts/boards, i suggest we introduce a navigation right above the list, which displays the account&Board, similar to the navigation in the nextcloud web-ui.
When the user wants to change the account, he or she clicks on the account icon/name, and then the list below gets updated to show the available accounts. When the user clicks one, the navbar gets updated, and the list shows the boards of that account. Again, when a board is selected, the navbar gets updated, and the lists of that board is shown.

This creates a 'flow' that reduces necessary clicks and (nearly)always shows a good selection. 

Drawbacks: 
The assumption is that moving a card between lists is the most common, and may not be always true.
It also may be necessary to properly communicate what that navbar does.

I'll try to create a mockup later

**Comment by newhinton** [comment]
A very basic mockup ;)

Some things that are not really visible: the current list containing the card to be moved should be highlighted until a new selection was made.


![grafik](https://user-images.githubusercontent.com/25279821/117583642-93a74600-b108-11eb-867f-a04c17cfe67d.png)

**Comment by stefan-niedermann** [comment]
Sounds good and should result in one click less in by far most cases 🙂  However i am not yet super satisified with the mock up because
- i fear that it won't scale good for long account and board names
- The board color (which is quicker scannable) isn't visible anymore and some orientation is missing therefore (we need to keep the board title, for accessibility reasons though)

I will ask the Nextcloud designers, maybe someone has another ideam

**Comment by newhinton** [comment]
Yeah, this design propably has issues with long names. However, boardcolors could be added rather easily with the dot, however this will only increase the length of that bar. It would work flawless in the listview though.


Maybe the accountname could be split in two rows, with the first row containing the Username and the second one the serveradress. I dont know how well that would in reality, but it would decrease it a bit, especially when the adress is treated as a subtitle with a lighter font and smaller size

**Comment by TtuxX** [comment]
Besides all this, just a little suggestion for improving current "Move Card" dialog:

- Remember the last selected list (if a card has already been moved in the past inside this board) instead of preselecting the current list.

Real life use case: 
I often move cards from "WIP" list to "Done" list. When I update my board, I sometimes move several cards one after the other. 
I think that replaying the last action selections could nicely reduce the number of interactions needed when moving several cards one after the other! :)

**Comment by stefan-niedermann** [comment]
Maybe something like that:

![grafik](https://user-images.githubusercontent.com/4741199/120988338-c29fee80-c77e-11eb-986d-6cd7663c08e6.png)

Compared to the [suggestion by @newhinton](https://github.com/stefan-niedermann/nextcloud-deck/issues/972#issuecomment-835863354) this solution
- Hides the account name
  - Clicking on it should expand a list, where each list item looks like today, so one can distinguish even if the images are the same
- Removes noisy wording like "Select a List:"
- Introduces a state (with a currently selected list)
  - This is required because we are reusing this component in various places, where we need a state for the current selection
- Account should only be visible if there is more than one account
- Board should only be visible if there is more than one board

**Comment by newhinton** [comment]
It looks good, but does it "flow"? The current dialog does not allow for quick changes, as you have to always use the dropdown, so to move a card between boards you would have to make 4 clicks to select it. Your mockup does not seem to change that, you still need to first open the dropdown, and then select a board and a card.

Do i misunderstand your mockup's dialog-flow?

**Comment by stefan-niedermann** [comment]
Account, board and list are preselected, so the proposal requires one click less than the current implementation. Quicker is only drag and drop 😉 
The option to change the target account and board need to stay.

**Comment by newhinton** [comment]
> The option to change the target account and board need to stay.
Yes, most certainly! I never meant to propose to remove those :D I imaged my initial mockup quite similar to how folders work, you can only select in your current folder, and if you go back the list shows you every available folder in that selection (Our folders here are the accounts, which contain "board-folders" which then contain "list-folders")

**Comment by stefan-niedermann** [comment]
This seems to be a common workflow on iOS, haven't often seen this on Android yet. Actually moving a card to another board takes the exact same steps with your and my proposal :shrug: :
Yours: Switch back to board "folder", select a board
Mine: Tap on the board chooser, select a board

**Comment by stefan-niedermann** [comment]
Some updates here: The next version will feature a slightly reworked move dialog which allows selecting the target list directly:

![Screenshot_20230309-102853_Nextcloud Deck](https://user-images.githubusercontent.com/4741199/223979219-2d38d451-c44a-489f-adec-8947b88ba593.png)

**Comment by TtuxX** [comment]
Great, many thanks ! :) Is it possible also to make it remember/preselect the last selected list ? (useful when moving several cards in a row)

**Comment by stefan-niedermann** [comment]
> Is it possible also to make it remember/preselect the last selected list ?

I get your point, but no: Preselected is the stack where the card is for a better orientation. Otherwise it would be quite confusing and also the context would be discussable (Remember moved target per account? board? per stack? depending on the origin board? ...), so we currently do not have any plans to change the behavior. Thanks for the feedback though!
