### ISSUE TITLE
After creating a new board, display it

### ISSUE THREAD

**Issue by sunjam** [stefan-niedermann/nextcloud-deck#98]
**Is your feature request related to a problem? Please describe.**
I successfully created a new board, but am not shown it until I browse back to the menu and select it.  It would be nice to have some small confirmation that the board has been created if it is not automatically displayed.

**Describe the solution you'd like**
After creating a new board by title and color, it would make sense for the board to be automatically displayed in the mobile app.

Thanks for considering!

**Comment by desperateCoder** [comment]
Hi @sunjam,

Thank you for your contribution! This makes sense, but please be patient. We have a lot more functionalities to implement, but maybe it isn't that complicated and @stefan-niedermann will fix that together with other improvements.

Our focus right now is on more critical issues, so please don't be mad if this isn't fixed in the next release. It will be fixed for sure!

**Comment by stefan-niedermann** [comment]
Okay, some work has been done here - if one creates a new board, it will be displayed directly.
**but**: You will have to create a new stack to work with this new board and this currently causes a NPE in the SyncManager#createStack().

```java
FullBoard board = dataBaseAdapter.getFullBoardByLocalIdDirectly(accountId, stack.getBoardId());
FullStack fullStack = new FullStack();
stack.setAccountId(accountId);
stack.setBoardId(board.getLocalId());
```

The main problem is, that `board` is `null` here, but it should not since `accountId` and `stack.getBoardId()` seem to be filled correctly. Maybe a local/remote Id problem?

The last line seems pretty odd, because we set the Id from the board, which we previously used to get the board in the first place. This means, the boardId is already set, isn't it?

Maybe @desperateCoder can have a look at this thingy?

**Comment by stefan-niedermann** [comment]
Should work with version 0.0.6 and on latest master. Please reopen if still issues occur. Thanks for reporting :)
